[[aggs-high-level]]

== 高阶概念

类似于查询表达式，((("聚合", "高阶概念")))聚合也有 _可组合_ 的语法：独立的方法可以被混合起来提供你需要的功能。这意味着只需要学习很少的基本概念，就可以得到几乎无尽的组合。

要掌握聚合，你只需要明白两个主要的概念：

 _桶_ :: 满足特定条件的文档的集合

 _指标_ :: 对桶内的文档进行统计计算

这就是全部了！每个聚合都是一个或者多个桶和零个或者多个指标的组合。用下面的SQL语句来解释吧：

[source,sql]
--------------------------------------------------
SELECT COUNT(color) <1>
FROM table
GROUP BY color <2>
--------------------------------------------------
<1> `COUNT(color)` 相当于指标。

<2> `GROUP BY color` 相当于桶。

桶非常类似于SQL的分组（GROUP BY），而指标非常类似于`COUNT()`、`SUM()`、`MAX()`等等统计方法。


让我们深入这两个概念((("聚合", "高阶概念", "桶")))((("桶")))并且了解和这两个概念相关的东西。

[role="pagebreak-before"]
=== 桶

 _桶_ 简单来说就是满足特定条件的文档的集合：

- 一个雇员属于 _男性_ 桶或者 _女性_ 桶

- 奥尔巴尼属于 _纽约_ 桶

- 日期2014-10-28属于 _十月_ 桶

当聚合开始被执行，每个文档里面的值通过计算来决定符合哪个桶的条件。然后，文档将放入相应的桶并接着进行聚合操作。

桶也可以被嵌套在其他桶里面，提供层次化的或者有条件的划分方案。例如，辛辛那提会被放入俄亥俄州这个桶，而 _整个_ 俄亥俄州桶会被放入美国这个桶。

Elasticsearch 有很多种类型的桶，能让你通过很多种方式来划分文档（时间、最受欢迎的词、年龄区间、地理位置等等）。其实根本上都是通过同样的原理进行操作：基于条件来划分文档。

=== 指标

桶能让我们划分文档到有意义的集合，((("聚合", "高阶概念", "指标")))((("指标")))但是最后我们需要的是对这些桶内的文档进行一些指标的计算。分桶是一种达到目的的手段：它提供了一种给文档分组的方法来让我们可以计算感兴趣的指标。

大多数 _指标_ 是简单的数学运算（例如最小值、平均值、最大值，还有汇总），这些是通过文档的值来计算。在实践中，指标能让你计算像平均薪资、最高出售价格、95%的查询延迟这样的数据。

=== 桶和指标的组合

 _聚合_ 是由桶和指标组成的。((("聚合", "高阶概念", "桶和指标的组合")))((("桶", "和指标的组合")))((("指标", "和桶的组合")))聚合可能只有一个桶，可能有一个指标，或者可能两个都有。也有可能有一些桶嵌套在其他桶里面。例如，我们可以通过所属国家来划分文档（桶），然后计算每个国家的平均薪酬（指标）。

由于桶可以被嵌套，我们可以实现非常多并且非常复杂的聚合：

1.通过国家划分文档（桶）

2.然后通过性别划分每个国家桶（桶）

3.然后通过年龄划分每个年龄桶（桶）

4.最后，为每个年龄区间计算平均薪酬（指标）

这将会告诉你每个 `<国家, 性别, 年龄>` 组合的平均薪酬。所有的这些都在一个请求并且遍历一次数据完成！
